<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("countries")->insert([
["name"=>"Afghanistan", "code" =>"AF / AFG", "phone_code" =>"93"],
["name"=>"Albania", "code" =>"AL / ALB", "phone_code" =>"355"],
["name"=>"Algeria", "code" =>"DZ / DZA", "phone_code" =>"213"],
["name"=>"American Samoa", "code" =>"AS / ASM", "phone_code" =>"1,684"],
["name"=>"Andorra", "code" =>"AD / AND", "phone_code" =>"376"],
["name"=>"Angola", "code" =>"AO / AGO", "phone_code" =>"244"],
["name"=>"Anguilla", "code" =>"AI / AIA", "phone_code" =>"1,264"],
["name"=>"Antarctica", "code" =>"AQ / ATA", "phone_code" =>"672, 64"],
["name"=>"Antigua and Barbuda", "code" =>"AG / ATG", "phone_code" =>"1,268"],
["name"=>"Argentina", "code" =>"AR / ARG", "phone_code" =>"54"],
["name"=>"Armenia", "code" =>"AM / ARM", "phone_code" =>"374"],
["name"=>"Aruba", "code" =>"AW / ABW", "phone_code" =>"297"],
["name"=>"Ascension Island", "code" =>"AC/ASC", "phone_code" =>"247"],
["name"=>"Australia", "code" =>"AU / AUS", "phone_code" =>"61"],
["name"=>"Austria", "code" =>"AT / AUT", "phone_code" =>"43"],
["name"=>"Azerbaijan", "code" =>"AZ / AZE", "phone_code" =>"994"],
["name"=>"Bahamas", "code" =>"BS / BHS", "phone_code" =>"1,242"],
["name"=>"Bahrain", "code" =>"BH / BHR", "phone_code" =>"973"],
["name"=>"Bangladesh", "code" =>"BD / BGD", "phone_code" =>"880"],
["name"=>"Barbados", "code" =>"BB / BRB", "phone_code" =>"1,246"],
["name"=>"Belarus", "code" =>"BY / BLR", "phone_code" =>"375"],
["name"=>"Belgium", "code" =>"BE / BEL", "phone_code" =>"32"],
["name"=>"Belize", "code" =>"BZ / BLZ", "phone_code" =>"501"],
["name"=>"Benin", "code" =>"BJ / BEN", "phone_code" =>"229"],
["name"=>"Bermuda", "code" =>"BM / BMU", "phone_code" =>"1,441"],
["name"=>"Bhutan", "code" =>"BT / BTN", "phone_code" =>"975"],
["name"=>"Bolivia", "code" =>"BO / BOL", "phone_code" =>"591"],
["name"=>"Bosnia and Herzegovina", "code" =>"BA / BIH", "phone_code" =>"387"],
["name"=>"Botswana", "code" =>"BW / BWA", "phone_code" =>"267"],
["name"=>"Brazil", "code" =>"BR / BRA", "phone_code" =>"55"],
["name"=>"British Virgin Islands", "code" =>"VG / VGB", "phone_code" =>"1,284"],
["name"=>"Brunei", "code" =>"BN / BRN", "phone_code" =>"673"],
["name"=>"Bulgaria", "code" =>"BG / BGR", "phone_code" =>"359"],
["name"=>"Burkina Faso", "code" =>"BF / BFA", "phone_code" =>"226"],
["name"=>"Burma (Myanmar)", "code" =>"MM / MMR", "phone_code" =>"95"],
["name"=>"Burundi", "code" =>"BI / BDI", "phone_code" =>"257"],
["name"=>"Cambodia", "code" =>"KH / KHM", "phone_code" =>"855"],
["name"=>"Cameroon", "code" =>"CM / CMR", "phone_code" =>"237"],
["name"=>"Canada", "code" =>"CA / CAN", "phone_code" =>"1"],
["name"=>"Cape Verde", "code" =>"CV / CPV", "phone_code" =>"238"],
["name"=>"Cayman Islands", "code" =>"KY / CYM", "phone_code" =>"1,345"],
["name"=>"Central African Republic", "code" =>"CF / CAF", "phone_code" =>"236"],
["name"=>"Chad", "code" =>"TD / TCD", "phone_code" =>"235"],
["name"=>"Chile", "code" =>"CL / CHL", "phone_code" =>"56"],
["name"=>"China", "code" =>"CN / CHN", "phone_code" =>"86"],
["name"=>"Christmas Island", "code" =>"CX / CXR", "phone_code" =>"61"],
["name"=>"Cocos (Keeling) Islands", "code" =>"CC / CCK", "phone_code" =>"61"],
["name"=>"Colombia", "code" =>"CO / COL", "phone_code" =>"57"],
["name"=>"Comoros", "code" =>"KM / COM", "phone_code" =>"269"],
["name"=>"Congo", "code" =>"CG / COG", "phone_code" =>"242"],
["name"=>"Cook Islands", "code" =>"CK / COK", "phone_code" =>"682"],
["name"=>"Costa Rica", "code" =>"CR / CRC", "phone_code" =>"506"],
["name"=>"Croatia", "code" =>"HR / HRV", "phone_code" =>"385"],
["name"=>"Cuba", "code" =>"CU / CUB", "phone_code" =>"53"],
["name"=>"Cyprus", "code" =>"CY / CYP", "phone_code" =>"357"],
["name"=>"Czech Republic", "code" =>"CZ / CZE", "phone_code" =>"420"],
["name"=>"Democratic Republic of the Congo", "code" =>"CD / COD", "phone_code" =>"243"],
["name"=>"Denmark", "code" =>"DK / DNK", "phone_code" =>"45"],
["name"=>"Diego Garcia", "code" =>"DG/DGA", "phone_code" =>"246"],
["name"=>"Djibouti", "code" =>"DJ / DJI", "phone_code" =>"253"],
["name"=>"Dominica", "code" =>"DM / DMA", "phone_code" =>"1,767"],
["name"=>"Dominican Republic", "code" =>"DO / DOM", "phone_code" =>"1 809, 1 829, 1 849"],
["name"=>"Ecuador", "code" =>"EC / ECU", "phone_code" =>"593"],
["name"=>"Egypt", "code" =>"EG / EGY", "phone_code" =>"20"],
["name"=>"El Salvador", "code" =>"SV / SLV", "phone_code" =>"503"],
["name"=>"Equatorial Guinea", "code" =>"GQ / GNQ", "phone_code" =>"240"],
["name"=>"Eritrea", "code" =>"ER / ERI", "phone_code" =>"291"],
["name"=>"Estonia", "code" =>"EE / EST", "phone_code" =>"372"],
["name"=>"Ethiopia", "code" =>"ET / ETH", "phone_code" =>"251"],
["name"=>"Falkland Islands", "code" =>"FK / FLK", "phone_code" =>"500"],
["name"=>"Faroe Islands", "code" =>"FO / FRO", "phone_code" =>"298"],
["name"=>"Fiji", "code" =>"FJ / FJI", "phone_code" =>"679"],
["name"=>"Finland", "code" =>"FI / FIN", "phone_code" =>"358"],
["name"=>"France", "code" =>"FR / FRA", "phone_code" =>"33"],
["name"=>"French Guiana", "code" =>"GF / GUF", "phone_code" =>"594"],
["name"=>"French Polynesia", "code" =>"PF / PYF", "phone_code" =>"689"],
["name"=>"Gabon", "code" =>"GA / GAB", "phone_code" =>"241"],
["name"=>"Gambia", "code" =>"GM / GMB", "phone_code" =>"220"],
["name"=>"Georgia", "code" =>"GE / GEO", "phone_code" =>"995"],
["name"=>"Germany", "code" =>"DE / DEU", "phone_code" =>"49"],
["name"=>"Ghana", "code" =>"GH / GHA", "phone_code" =>"233"],
["name"=>"Gibraltar", "code" =>"GI / GIB", "phone_code" =>"350"],
["name"=>"Greece", "code" =>"GR / GRC", "phone_code" =>"30"],
["name"=>"Greenland", "code" =>"GL / GRL", "phone_code" =>"299"],
["name"=>"Grenada", "code" =>"GD / GRD", "phone_code" =>"1,473"],
["name"=>"Guadeloupe", "code" =>"GP / GLP", "phone_code" =>"590"],
["name"=>"Guam", "code" =>"GU / GUM", "phone_code" =>"1,671"],
["name"=>"Guatemala", "code" =>"GT / GTM", "phone_code" =>"502"],
["name"=>"Guinea", "code" =>"GN / GIN", "phone_code" =>"224"],
["name"=>"Guinea-Bissau", "code" =>"GW / GNB", "phone_code" =>"245"],
["name"=>"Guyana", "code" =>"GY / GUY", "phone_code" =>"592"],
["name"=>"Haiti", "code" =>"HT / HTI", "phone_code" =>"509"],
["name"=>"Holy See (Vatican City)", "code" =>"VA / VAT", "phone_code" =>"39"],
["name"=>"Honduras", "code" =>"HN / HND", "phone_code" =>"504"],
["name"=>"Hong Kong", "code" =>"HK / HKG", "phone_code" =>"852"],
["name"=>"Hungary", "code" =>"HU / HUN", "phone_code" =>"36"],
["name"=>"Iceland", "code" =>"IS / IS", "phone_code" =>"354"],
["name"=>"India", "code" =>"IN / IND", "phone_code" =>"91"],
["name"=>"Indonesia", "code" =>"ID / IDN", "phone_code" =>"62"],
["name"=>"Iran", "code" =>"IR / IRN", "phone_code" =>"98"],
["name"=>"Iraq", "code" =>"IQ / IRQ", "phone_code" =>"964"],
["name"=>"Ireland", "code" =>"IE / IRL", "phone_code" =>"353"],
["name"=>"Isle of Man", "code" =>"IM / IMN", "phone_code" =>"44"],
["name"=>"Israel", "code" =>"IL / ISR", "phone_code" =>"972"],
["name"=>"Italy", "code" =>"IT / ITA", "phone_code" =>"39"],
["name"=>"Ivory Coast (Côte d'Ivoire)", "code" =>"CI / CIV", "phone_code" =>"225"],
["name"=>"Jamaica", "code" =>"JM / JAM", "phone_code" =>"1,876"],
["name"=>"Japan", "code" =>"JP / JPN", "phone_code" =>"81"],
["name"=>"Jersey", "code" =>"JE / JEY", "phone_code" =>"44"],
["name"=>"Jordan", "code" =>"JO / JOR", "phone_code" =>"962"],
["name"=>"Kazakhstan", "code" =>"KZ / KAZ", "phone_code" =>"7"],
["name"=>"Kenya", "code" =>"KE / KEN", "phone_code" =>"254"],
["name"=>"Kiribati", "code" =>"KI / KIR", "phone_code" =>"686"],
["name"=>"Kuwait", "code" =>"KW / KWT", "phone_code" =>"965"],
["name"=>"Kyrgyzstan", "code" =>"KG / KGZ", "phone_code" =>"996"],
["name"=>"Laos", "code" =>"LA / LAO", "phone_code" =>"856"],
["name"=>"Latvia", "code" =>"LV / LVA", "phone_code" =>"371"],
["name"=>"Lebanon", "code" =>"LB / LBN", "phone_code" =>"961"],
["name"=>"Lesotho", "code" =>"LS / LSO", "phone_code" =>"266"],
["name"=>"Liberia", "code" =>"LR / LBR", "phone_code" =>"231"],
["name"=>"Libya", "code" =>"LY / LBY", "phone_code" =>"218"],
["name"=>"Liechtenstein", "code" =>"LI / LIE", "phone_code" =>"423"],
["name"=>"Lithuania", "code" =>"LT / LTU", "phone_code" =>"370"],
["name"=>"Luxembourg", "code" =>"LU / LUX", "phone_code" =>"352"],
["name"=>"Macau", "code" =>"MO / MAC", "phone_code" =>"853"],
["name"=>"Macedonia", "code" =>"MK / MKD", "phone_code" =>"389"],
["name"=>"Madagascar", "code" =>"MG / MDG", "phone_code" =>"261"],
["name"=>"Malawi", "code" =>"MW / MWI", "phone_code" =>"265"],
["name"=>"Malaysia", "code" =>"MY / MYS", "phone_code" =>"60"],
["name"=>"Maldives", "code" =>"MV / MDV", "phone_code" =>"960"],
["name"=>"Mali", "code" =>"ML / MLI", "phone_code" =>"223"],
["name"=>"Malta", "code" =>"MT / MLT", "phone_code" =>"356"],
["name"=>"Marshall Islands", "code" =>"MH / MHL", "phone_code" =>"692"],
["name"=>"Martinique", "code" =>"MQ / MTQ", "phone_code" =>"596"],
["name"=>"Mauritania", "code" =>"MR / MRT", "phone_code" =>"222"],
["name"=>"Mauritius", "code" =>"MU / MUS", "phone_code" =>"230"],
["name"=>"Mayotte", "code" =>"YT / MYT", "phone_code" =>"262"],
["name"=>"Mexico", "code" =>"MX / MEX", "phone_code" =>"52"],
["name"=>"Micronesia", "code" =>"FM / FSM", "phone_code" =>"691"],
["name"=>"Moldova", "code" =>"MD / MDA", "phone_code" =>"373"],
["name"=>"Monaco", "code" =>"MC / MCO", "phone_code" =>"377"],
["name"=>"Mongolia", "code" =>"MN / MNG", "phone_code" =>"976"],
["name"=>"Montenegro", "code" =>"ME / MNE", "phone_code" =>"382"],
["name"=>"Montserrat", "code" =>"MS / MSR", "phone_code" =>"1,664"],
["name"=>"Morocco", "code" =>"MA / MAR", "phone_code" =>"212"],
["name"=>"Mozambique", "code" =>"MZ / MOZ", "phone_code" =>"258"],
["name"=>"Namibia", "code" =>"NA / NAM", "phone_code" =>"264"],
["name"=>"Nauru", "code" =>"NR / NRU", "phone_code" =>"674"],
["name"=>"Nepal", "code" =>"NP / NPL", "phone_code" =>"977"],
["name"=>"Netherlands", "code" =>"NL / NLD", "phone_code" =>"31"],
["name"=>"Netherlands Antilles", "code" =>"AN / ANT", "phone_code" =>"599"],
["name"=>"New Caledonia", "code" =>"NC / NCL", "phone_code" =>"687"],
["name"=>"New Zealand", "code" =>"NZ / NZL", "phone_code" =>"64"],
["name"=>"Nicaragua", "code" =>"NI / NIC", "phone_code" =>"505"],
["name"=>"Niger", "code" =>"NE / NER", "phone_code" =>"227"],
["name"=>"Nigeria", "code" =>"NG / NGA", "phone_code" =>"234"],
["name"=>"Niue", "code" =>"NU / NIU", "phone_code" =>"683"],
["name"=>"Norfolk Island", "code" =>"NF / NFK", "phone_code" =>"672"],
["name"=>"North Korea", "code" =>"KP / PRK", "phone_code" =>"850"],
["name"=>"Northern Mariana Islands", "code" =>"MP / MNP", "phone_code" =>"1,670"],
["name"=>"Norway", "code" =>"NO / NOR", "phone_code" =>"47"],
["name"=>"Oman", "code" =>"OM / OMN", "phone_code" =>"968"],
["name"=>"Pakistan", "code" =>"PK / PAK", "phone_code" =>"92"],
["name"=>"Palau", "code" =>"PW / PLW", "phone_code" =>"680"],
["name"=>"Palestine", "code" =>"PS / PSE", "phone_code" =>"970"],
["name"=>"Panama", "code" =>"PA / PAN", "phone_code" =>"507"],
["name"=>"Papua New Guinea", "code" =>"PG / PNG", "phone_code" =>"675"],
["name"=>"Paraguay", "code" =>"PY / PRY", "phone_code" =>"595"],
["name"=>"Peru", "code" =>"PE / PER", "phone_code" =>"51"],
["name"=>"Philippines", "code" =>"PH / PHL", "phone_code" =>"63"],
["name"=>"Pitcairn Islands", "code" =>"PN / PCN", "phone_code" =>"870"],
["name"=>"Poland", "code" =>"PL / POL", "phone_code" =>"48"],
["name"=>"Portugal", "code" =>"PT / PRT", "phone_code" =>"351"],
["name"=>"Puerto Rico", "code" =>"PR / PRI", "phone_code" =>"1 787, 1 939"],
["name"=>"Qatar", "code" =>"QA / QAT", "phone_code" =>"974"],
["name"=>"Republic of the Congo", "code" =>"CG / COG", "phone_code" =>"242"],
["name"=>"Reunion Island", "code" =>"RE / REU", "phone_code" =>"262"],
["name"=>"Romania", "code" =>"RO / ROU", "phone_code" =>"40"],
["name"=>"Russia", "code" =>"RU / RUS", "phone_code" =>"7"],
["name"=>"Rwanda", "code" =>"RW / RWA", "phone_code" =>"250"],
["name"=>"Saint Barthelemy", "code" =>"BL / BLM", "phone_code" =>"590"],
["name"=>"Saint Helena", "code" =>"SH / SHN", "phone_code" =>"290"],
["name"=>"Saint Kitts and Nevis", "code" =>"KN / KNA", "phone_code" =>"1,869"],
["name"=>"Saint Lucia", "code" =>"LC / LCA", "phone_code" =>"1,758"],
["name"=>"Saint Martin", "code" =>"MF / MAF", "phone_code" =>"590"],
["name"=>"Saint Pierre and Miquelon", "code" =>"PM / SPM", "phone_code" =>"508"],
["name"=>"Saint Vincent and the Grenadines", "code" =>"VC / VCT", "phone_code" =>"1,784"],
["name"=>"Samoa", "code" =>"WS / WSM", "phone_code" =>"685"],
["name"=>"San Marino", "code" =>"SM / SMR", "phone_code" =>"378"],
["name"=>"Sao Tome and Principe", "code" =>"ST / STP", "phone_code" =>"239"],
["name"=>"Saudi Arabia", "code" =>"SA / SAU", "phone_code" =>"966"],
["name"=>"Senegal", "code" =>"SN / SEN", "phone_code" =>"221"],
["name"=>"Serbia", "code" =>"RS / SRB", "phone_code" =>"381"],
["name"=>"Seychelles", "code" =>"SC / SYC", "phone_code" =>"248"],
["name"=>"Sierra Leone", "code" =>"SL / SLE", "phone_code" =>"232"],
["name"=>"Singapore", "code" =>"SG / SGP", "phone_code" =>"65"],
["name"=>"Sint Maarten", "code" =>"SX / SXM", "phone_code" =>"1,721"],
["name"=>"Slovakia", "code" =>"SK / SVK", "phone_code" =>"421"],
["name"=>"Slovenia", "code" =>"SI / SVN", "phone_code" =>"386"],
["name"=>"Solomon Islands", "code" =>"SB / SLB", "phone_code" =>"677"],
["name"=>"Somalia", "code" =>"SO / SOM", "phone_code" =>"252"],
["name"=>"South Africa", "code" =>"ZA / ZAF", "phone_code" =>"27"],
["name"=>"South Korea", "code" =>"KR / KOR", "phone_code" =>"82"],
["name"=>"South Sudan", "code" =>"SS / SSD", "phone_code" =>"211"],
["name"=>"Spain", "code" =>"ES / ESP", "phone_code" =>"34"],
["name"=>"Sri Lanka", "code" =>"LK / LKA", "phone_code" =>"94"],
["name"=>"Sudan", "code" =>"SD / SDN", "phone_code" =>"249"],
["name"=>"Suriname", "code" =>"SR / SUR", "phone_code" =>"597"],
["name"=>"Svalbard", "code" =>"SJ / SJM", "phone_code" =>"47"],
["name"=>"Swaziland", "code" =>"SZ / SWZ", "phone_code" =>"268"],
["name"=>"Sweden", "code" =>"SE / SWE", "phone_code" =>"46"],
["name"=>"Switzerland", "code" =>"CH / CHE", "phone_code" =>"41"],
["name"=>"Syria", "code" =>"SY / SYR", "phone_code" =>"963"],
["name"=>"Taiwan", "code" =>"TW / TWN", "phone_code" =>"886"],
["name"=>"Tajikistan", "code" =>"TJ / TJK", "phone_code" =>"992"],
["name"=>"Tanzania", "code" =>"TZ / TZA", "phone_code" =>"255"],
["name"=>"Thailand", "code" =>"TH / THA", "phone_code" =>"66"],
["name"=>"Timor-Leste (East Timor)", "code" =>"TL / TLS", "phone_code" =>"670"],
["name"=>"Togo", "code" =>"TG / TGO", "phone_code" =>"228"],
["name"=>"Tokelau", "code" =>"TK / TKL", "phone_code" =>"690"],
["name"=>"Tonga Islands", "code" =>"TO / TON", "phone_code" =>"676"],
["name"=>"Trinidad and Tobago", "code" =>"TT / TTO", "phone_code" =>"1,868"],
["name"=>"Tunisia", "code" =>"TN / TUN", "phone_code" =>"216"],
["name"=>"Turkey", "code" =>"TR / TUR", "phone_code" =>"90"],
["name"=>"Turkmenistan", "code" =>"TM / TKM", "phone_code" =>"993"],
["name"=>"Turks and Caicos Islands", "code" =>"TC / TCA", "phone_code" =>"1,649"],
["name"=>"Tuvalu", "code" =>"TV / TUV", "phone_code" =>"688"],
["name"=>"Uganda", "code" =>"UG / UGA", "phone_code" =>"256"],
["name"=>"Ukraine", "code" =>"UA / UKR", "phone_code" =>"380"],
["name"=>"United Arab Emirates", "code" =>"AE / ARE", "phone_code" =>"971"],
["name"=>"United Kingdom", "code" =>"GB / GBR", "phone_code" =>"44"],
["name"=>"United States", "code" =>"US / USA", "phone_code" =>"1"],
["name"=>"Uruguay", "code" =>"UY / URY", "phone_code" =>"598"],
["name"=>"US Virgin Islands", "code" =>"VI / VIR", "phone_code" =>"1,340"],
["name"=>"Uzbekistan", "code" =>"UZ / UZB", "phone_code" =>"998"],
["name"=>"Vanuatu", "code" =>"VU / VUT", "phone_code" =>"678"],
["name"=>"Venezuela", "code" =>"VE / VEN", "phone_code" =>"58"],
["name"=>"Vietnam", "code" =>"VN / VNM", "phone_code" =>"84"],
["name"=>"Wallis and Futuna", "code" =>"WF / WLF", "phone_code" =>"681"],
["name"=>"Western Sahara", "code" =>"EH / ESH", "phone_code" =>"212"],
["name"=>"Yemen", "code" =>"YE / YEM", "phone_code" =>"967"],
["name"=>"Zambia", "code" =>"ZM / ZMB", "phone_code" =>"260"],
["name"=>"Zimbabwe", "code" =>"ZW / ZWE", "phone_code" =>"263"],
        ]);
    }
}
